#!/usr/bin/env bash
# Fizz Buzz
i=0
while [ $i -lt 100 ]; do
	(( i+=1 ))
	if (( i % 3 == 0 )) && (( i % 5 == 0 )); then
		echo "FizzBuzz"
	continue
	elif (( i % 3 == 0 )); then
		echo "Fizz"
	continue
	elif (( i % 5 == 0 )); then
		echo "Buzz"
	continue
	fi
	echo "$i"
done