#!/usr/bin/env bash
# This script is displaying superstitious
i=1

while ((i <= 20)); do
    echo "$i"
    if [ $i == 4 ]
    then
        echo "bad luck from China"
    elif [ $i == 9 ]
    then
        echo "good luck from Japan"
    elif [ $i == 17 ]
    then
        echo "bad luck from Italy"
    fi
    i=$((i+ 1))
done