#!/usr/bin/env bash
# This script is displaying superstitious
i=1

while ((i <= 20)); do
    echo "$i"
    case $i in
    4) echo "bad luck from China"
    ;;
    9) echo "good luck from Japan"
    ;;
    17) echo "bad luck from Italy"
    ;;
    esac

    i=$((i+ 1))
done