#!/usr/bin/env bash

file=school
if test -e $file;
then
    echo "$file file exists"
    if [ -f $file ]
    then
        echo "$file file is not empty"
	else
		echo "$file file is empty"
    fi
    if test -f "$file"; then
		echo "$file is a regular file"
    fi
else
    echo "$file file does not exist"
fi